### ISSUE TITLE
Investigar / ver tutoriales sobre ReactJs 

### ISSUE THREAD

**Issue by magalopez** [magalopez/LIM009-fe-burger-queen#2]

**Comment by yenifergalarza** [comment]
-  hooks vs components
https://medium.com/@ger86/react-components-vs-react-hooks-f5d6d507f42e
- redux 

- status

- render

-errores comunes en react
https://rvaccaro.com.ar/2018/05/errores-comunes-cuando-empezamos-a-utilizar-react/
https://blog.michelletorres.mx/3-tipicos-errores-en-react-y-como-evitarlos/

-desplegar react en github pages
https://blog.michelletorres.mx/deploy-de-una-aplicacion-react-a-github-pages/

-eventos en react
https://medium.com/@simonhoyos/eventos-en-react-b53179ec9683

-workbox
https://developers.google.com/web/tools/workbox/

-pwa
https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/?hl=es
https://developers.google.com/web/tools/lighthouse/?hl=es

Tu primera Progressive Web App
